name: "Terraform"

on:
  push:
    branches: ["main", "develop"]

jobs:
  terraform-plan:
    name: "Terraform Plan"
    permissions:
      id-token: write
      contents: read
    runs-on: self-hosted
    container: docker.io/hashicorp/terraform:1.6
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::676791758112:role/RoleForGithubActions
          role-session-name: github-deploy
          aws-region: ap-southeast-1

      - name: Prepare TFVARS
        run: |
          git config --global --add safe.directory $(pwd)
          current_branch_name=$(git branch --show-current)
          if [[ current_branch_name == develop ]]; then
            cat <<EOF >> terraform-development.tfvars
            auth0_domain        = "${{ vars.AUTH0_DOMAIN }}"
            auth0_client_id     = "${{ vars.AUTH0_CLIENT_ID }}"
            auth0_client_secret = "${{ vars.AUTH0_CLIENT_SECRET }}"

            aws_ses_access_key_id     = "AKIAXXXXXXXXXXXXXXXX"
            aws_ses_secret_access_key = "7e8c2148xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
            aws_ses_region            = "us-east-1"

            google_client_id     = "my_google_client_id"
            google_client_secret = "my_google_client_secret"

            microsoft_client_id     = "my_microsoft_client_id"
            microsoft_client_secret = "my_microsoft_client_secret"
            EOF
          fi
          if [[ current_branch_name == main ]]; then
            cat <<EOF >> terraform-staging.tfvars
            auth0_domain        = "${{ vars.AUTH0_DOMAIN }}"
            auth0_client_id     = "${{ vars.AUTH0_CLIENT_ID }}"
            auth0_client_secret = "${{ vars.AUTH0_CLIENT_SECRET }}"

            aws_ses_access_key_id     = "AKIAXXXXXXXXXXXXXXXX"
            aws_ses_secret_access_key = "7e8c2148xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
            aws_ses_region            = "us-east-1"

            google_client_id     = "my_google_client_id"
            google_client_secret = "my_google_client_secret"

            microsoft_client_id     = "my_microsoft_client_id"
            microsoft_client_secret = "my_microsoft_client_secret"
            EOF
          fi

      - name: Terraform version
        run: terraform -version

      - name: Terraform Init
        run: terraform init

      - name: Select development workspace
        run: terraform workspace new development || terraform workspace select development

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color -var-file=terraform-$(terraform workspace show).tfvars

  deploy-development:
    if: github.ref == 'refs/heads/"develop"'
    name: "Deploy developmnet environment"
    permissions:
      id-token: write
      contents: read
    runs-on: self-hosted
    needs: terraform-plan
    container: docker.io/hashicorp/terraform:1.6
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::676791758112:role/RoleForGithubActions
          role-session-name: github-deploy
          aws-region: ap-southeast-1

      - name: Prepar TFVARS
        run: |
          git config --global --add safe.directory $(pwd)
          current_branch_name=$(git branch --show-current)
          if [[ current_branch_name == develop ]]; then
            cat <<EOF >> terraform-development.tfvars
            auth0_domain        = "${{ vars.AUTH0_DOMAIN }}"
            auth0_client_id     = "${{ vars.AUTH0_CLIENT_ID }}"
            auth0_client_secret = "${{ vars.AUTH0_CLIENT_SECRET }}"

            aws_ses_access_key_id     = "AKIAXXXXXXXXXXXXXXXX"
            aws_ses_secret_access_key = "7e8c2148xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
            aws_ses_region            = "us-east-1"

            google_client_id     = "my_google_client_id"
            google_client_secret = "my_google_client_secret"

            microsoft_client_id     = "my_microsoft_client_id"
            microsoft_client_secret = "my_microsoft_client_secret"
            EOF
          fi
          if [[ current_branch_name == main ]]; then
            cat <<EOF >> terraform-staging.tfvars
            auth0_domain        = "${{ vars.AUTH0_DOMAIN }}"
            auth0_client_id     = "${{ vars.AUTH0_CLIENT_ID }}"
            auth0_client_secret = "${{ vars.AUTH0_CLIENT_SECRET }}"

            aws_ses_access_key_id     = "AKIAXXXXXXXXXXXXXXXX"
            aws_ses_secret_access_key = "7e8c2148xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
            aws_ses_region            = "us-east-1"

            google_client_id     = "my_google_client_id"
            google_client_secret = "my_google_client_secret"

            microsoft_client_id     = "my_microsoft_client_id"
            microsoft_client_secret = "my_microsoft_client_secret"
            EOF
          fi

      - name: Terraform Init
        run: terraform init

      - name: Select development workspace
        run: terraform workspace new development || terraform workspace select development

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=terraform-$(terraform workspace show).tfvars
